[package]
name = "examples"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
menu = ["winit_tray/menu"]

[dependencies]
winit_tray.workspace = true
winit.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
image.workspace = true
softbuffer.workspace = true
vello_cpu.workspace = true
